#!/bin/bash

# Copyright 2024 ARMCNC, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Execute business after installation is completed

architecture=$(dpkg --print-architecture)

sudo ln -s /opt/armcnc/backend/release/main /usr/local/bin/armcnc

if [ ! -d "/opt/armcnc/.venv" ]; then
    # shellcheck disable=SC2164
    cd /opt/armcnc
    python3 -m venv .venv
    source .venv/bin/activate && pip install --upgrade pip
    pip install logging numpy==1.26.4 openai pyserial pyusb requests websocket-client==0.48.0
    pip install --upgrade armcnc -i https://mirrors.aliyun.com/pypi/simple
    deactivate
else
    # shellcheck disable=SC2164
    cd /opt/armcnc
    source .venv/bin/activate && pip install --upgrade pip
    pip install logging numpy==1.26.4 openai pyserial pyusb requests websocket-client==0.48.0
    pip install --upgrade armcnc -i https://mirrors.aliyun.com/pypi/simple
    deactivate
fi

if [ "$architecture" = "amd64" ]; then
    sudo rm -rf /usr/lib/linuxcnc/modules/cia402.so
    sudo mv /usr/lib/linuxcnc/modules/cia402_amd64.so /usr/lib/linuxcnc/modules/cia402.so
else
    sudo rm -rf /usr/lib/linuxcnc/modules/cia402_amd64.so
fi

if [ -f "/etc/nginx/nginx.conf" ]; then
    sudo sed -i 's/^\(\s*\)\(include \/etc\/nginx\/sites-enabled\/\*;\)/\1#\2/' /etc/nginx/nginx.conf
    sudo systemctl daemon-reload
    sudo systemctl restart nginx.service
fi

sudo ldconfig
sudo systemctl daemon-reload > /dev/null 2>&1
sudo systemctl restart lightdm.service
sudo systemctl enable armcnc_service.service > /dev/null 2>&1
sudo systemctl restart armcnc_service.service