#!/bin/bash

# Copyright 2024 ARMCNC, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Remove previously executed business

sudo rm -rf /usr/local/bin/armcnc

sudo systemctl stop armcnc_chromium.service
sudo systemctl disable armcnc_chromium.service > /dev/null 2>&1
sudo systemctl stop armcnc_launch.service
sudo systemctl disable armcnc_launch.service > /dev/null 2>&1
sudo systemctl stop armcnc_linuxcnc.service
sudo systemctl disable armcnc_linuxcnc.service > /dev/null 2>&1
sudo systemctl stop armcnc_service.service
sudo systemctl disable armcnc_service.service > /dev/null 2>&1

if [ -f "/etc/nginx/nginx.conf" ]; then
    sudo sed -i 's/^\(\s*\)#\(include \/etc\/nginx\/sites-enabled\/\*;\)/\1\2/' /etc/nginx/nginx.conf
    sudo systemctl daemon-reload
    sudo systemctl restart nginx.service
fi

sudo systemctl daemon-reload > /dev/null 2>&1

exit 0